### ISSUE TITLE
docker-machine cant on windows server?

### ISSUE THREAD

**Issue by fthamura** [StefanScherer/docker-windows-box#12]
i got your diagram, that docker-machine cant connect to windows server, is it right?

https://github.com/StefanScherer/docker-windows-box

F

**Comment by StefanScherer** [comment]
Yes, docker-machine can only connect to Linux machines right now. There is a PR https://github.com/docker/machine/pull/3329 that worked months ago for Azure and contains code to communicate with WinRM instead of SSH with a Windows machine.

But I use the following workaround
- Create the TLS certs on windows with my docker image dockertls, restarting the dockerd
- Copy the client certs to my Mac and adjust a config.json like in https://github.com/StefanScherer/dockerfiles-windows/issues/16 

With that I can `docker-machine env windows to set the environments to a local Windows VM or remote Azure VM with Docker + TLS.

**Comment by fthamura** [comment]
i got this?

https://docs.docker.com/machine/drivers/hyper-v/

is it different?

F

**Comment by StefanScherer** [comment]
This Hyper-V driver can be used to create a Linux Hyper-V VM (with boot2docker.iso).

This is the second picture of https://blog.docker.com/2016/10/considerations-running-docker-windows-server-2016-hyper-v-vms/

**Comment by StefanScherer** [comment]
I'll close this one because this this should be handled in docker/machine repo
