### ISSUE TITLE
Kubernetes?

### ISSUE THREAD

**Issue by StefanScherer** [StefanScherer/docker-windows-box#24]
I would love to have/see an easy Windows environment for a Kubernetes cluster as simple as `vagrant up`. :-)

**Comment by StefanScherer** [comment]
Here is a work in progress

https://github.com/PatrickLang/windows-k8s-lab/blob/kubeadm/README.md

**Comment by StefanScherer** [comment]
Look: https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows

**Comment by StefanScherer** [comment]
Here is a Vagrant env: https://github.com/rjmorse/kubernetes-windows-vagrant

**Comment by juliostanley** [comment]
Great stuff!

--- 

A few personal preferences/notes:

Instead of chocolatey I personally tend to use scoop:
https://github.com/lukesampson/scoop/wiki/Chocolatey-Comparison

I'll request for the nightly build of docker and dockerd to be available in the main scoop bucket next to the docker.json:
https://github.com/lukesampson/scoop/blob/master/bucket/docker.json

Nothing wrong with the Invoke-WebRequest and Expand, just prob slightly faster to do without it, and everything would be nicely packed into ~/scoop/apps

---

Also regarding the module at OneGet and installing it on Windows 10 Pro (its not possible due to an error):
https://github.com/OneGet/MicrosoftDockerProvider

Hope they take a look at the outstanding pull request (not possible to install on 10 pro)
https://github.com/OneGet/MicrosoftDockerProvider/pull/36

Here is another fix (although if not wrong the wildcard should be 'Microsoft Windows 10*' to no break non Pro versions)
https://github.com/lambdalisue/MicrosoftDockerProvider/commit/1c4185ef724f4c0603a2596ecdafab0bf16b15e1

**Comment by StefanScherer** [comment]
Closing this. I'm far away of setting up a Kubernetes environment and there are better repos out there where we should put our help into.
